"""add reports table

Revision ID: 4226f6cde25c
Revises: b7f9ed6623f0
Create Date: 2026-05-30 14:08:40.039636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4226f6cde25c'
down_revision: Union[str, None] = 'b7f9ed6623f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('week_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('story_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_created_at', 'reports', ['created_at'], unique=False)
    # NOTE: the HNSW index ix_articles_embedding_hnsw is created in migration
    # b7f9ed6623f0 but not declared on the model, so autogenerate proposed
    # dropping it. That drop is intentionally removed here to preserve the index.


def downgrade() -> None:
    op.drop_index('ix_reports_created_at', table_name='reports')
    op.drop_table('reports')
